docs: add Celestia-ContributorGitPOAP sections
celestiaorg/celestia-core pull request #1156
Opened 2023-12-16 13:29 UTC by SakiAoiaoi

Add Celestia Contributor GitPOPA sections to CONTRIBUTING
Close https://github.com/celestiaorg/celestia-core/issues/1155

- [ ✅] Tests written/updated
- [ ✅] Changelog entry added in `.changelog` (we use
  [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ✅] Updated relevant documentation (`docs/` or `spec/`) and code comments

2023-12-16 20:05 UTC, rootulp requested changes
I like the idea but I I'd rather we don't modify this file because this repo is a fork of upstream CometBFT and AFAIK there aren't any Celestia specific things in CONTRIBUTING.md.

If we minimize the diff, it's easier to pull changes from upstream.

2023-12-16 20:05 UTC, rootulp commented on CONTRIBUTING.md
> +Once your pull requests are merged to one of celestiaorg's GitHub repositories, you will be automatically awared  the right to mint a [Celestia Contributor GitPOAP](https://www.gitpoap.io/gh/celestia
```suggestion
Once your pull request is merged to an eligible celestiaorg GitHub repository, you will be rewarded the ability to mint a [GitPOAP](https://www.gitpoap.io). You can check which repositories are eligible at [gitpoap/celestiaorg](https://www.gitpoap.io/gh/celestiaorg)
```

2023-12-16 20:05 UTC, rootulp commented on CONTRIBUTING.md
> +
Too many new lines

```suggestion
```

2023-12-17 03:27 UTC, SakiAoiaoi commented on CONTRIBUTING.md
> +Once your pull requests are merged to one of celestiaorg's GitHub repositories, you will be automatically awared  the right to mint a [Celestia Contributor GitPOAP](https://www.gitpoap.io/gh/celestia
Thanks a lots!Your kind points motivate me so much.

2023-12-17 03:29 UTC, SakiAoiaoi commented on CONTRIBUTING.md
> +
Thanks a lot! Your kind points motivate me so much.

2023-12-17 07:08 UTC, SakiAoiaoi commented
I completely agree with you!!Thank you for your kind correcting me.

I think it would be better to add the GitPOAP explanation to the README, so I made a new pull request to the README to it.
https://github.com/celestiaorg/celestia-core/pull/1157

2023-12-20 13:45 UTC, closed without merging