Update careers link
celestiaorg/celestia-core pull request #787
Opened 2022-06-14 20:37 UTC by liamsi

Please add a description of the changes that this PR introduces and the files that
are the most critical to review.

If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.

2022-06-14 20:39 UTC, evan-forbes approved these changes

2022-06-14 21:04 UTC, adlerjohn requested changes

2022-06-14 21:04 UTC, adlerjohn commented on README.md
> +We are hiring Go engineers! Join us in building the future of blockchain scaling and interoperability. [Apply here]([https://angel.co/company/celestialabs/jobs](https://jobs.lever.co/celestia)).
This link is broken.
```suggestion
We are hiring Go engineers! Join us in building the future of blockchain scaling and interoperability. [Apply here](https://jobs.lever.co/celestia).
```

2022-06-15 13:09 UTC, adlerjohn approved these changes

2022-06-20 19:44 UTC, merged