QGB remove dependency on geth dependency for encoding the data root
celestiaorg/celestia-core pull request #937
Opened 2023-01-13 10:56 UTC by amityadav0

## Description

- Remove dependency on geth dependency for encoding the data root
- Manually pad the hex representation of the height to 32 bytes and concatenate the data root to it.

Closes: #934

2023-01-16 15:02 UTC, SweeXordious requested changes

2023-01-16 21:39 UTC, evan-forbes commented on rpc/core/blocks.go
> -// `abi.encode(...)` in Ethereum.
yeah, agree

2023-01-17 05:31 UTC, amityadav0 commented on rpc/core/blocks.go
> +	if l == length {
yes, updating it.

2023-01-17 05:31 UTC, amityadav0 commented on rpc/core/blocks.go
> -// `abi.encode(...)` in Ethereum.
got it.

2023-01-17 05:39 UTC, amityadav0 commented on rpc/core/blocks.go
> +	hexBytes, _ := hex.DecodeString(hexRepresentation)
done

2023-01-17 05:41 UTC, amityadav0 commented
@SweeXordious Thanks for the review. I have updated the code

2023-01-17 10:32 UTC, amityadav0 commented on rpc/core/blocks.go
> +// Pad bytes to given length
Thanks

2023-01-19 09:02 UTC, SweeXordious approved these changes

2023-01-23 17:09 UTC, merged